#!/bin/bash

CLIPBOARD_OUTGOING_PORT=9001
TMUX_BUFFER=`tmux save-buffer -`

if [ ! -z "$CLIPBOARD_OUTGOING_PORT" ] && [ ! -z "$TMUX" ]
then
  echo -ne '\x00' > ~/.tmux.clipboard
  echo "$TMUX_BUFFER" >> ~/.tmux.clipboard
  echo -e '\x00' >> ~/.tmux.clipboard
  cat ~/.tmux.clipboard | nc -q 1 localhost "$CLIPBOARD_OUTGOING_PORT"
  echo "done"
fi

if [ ! -z `which xsel` ]
then
  tmux save-buffer - | xsel -ib 2>/dev/null
  echo "done"
fi
